# Generated by Django 4.1.2 on 2022-10-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=30)),
                ('subject_code', models.CharField(max_length=30)),
                ('subject_credits', models.CharField(max_length=30)),
            ],
        ),
    ]
