# Generated by Django 4.1.2 on 2022-10-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='semester2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=30)),
                ('subject_code', models.CharField(max_length=30)),
                ('subject_credits', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='semester3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=30)),
                ('subject_code', models.CharField(max_length=30)),
                ('subject_credits', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='semester4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=30)),
                ('subject_code', models.CharField(max_length=30)),
                ('subject_credits', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='semester5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=30)),
                ('subject_code', models.CharField(max_length=30)),
                ('subject_credits', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='semester6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=30)),
                ('subject_code', models.CharField(max_length=30)),
                ('subject_credits', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='semester7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=30)),
                ('subject_code', models.CharField(max_length=30)),
                ('subject_credits', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='semester8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=30)),
                ('subject_code', models.CharField(max_length=30)),
                ('subject_credits', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='subjectModel',
            new_name='semester1',
        ),
    ]
