# Generated by Django 4.1.2 on 2022-10-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectApp', '0004_semestersmodel_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestersmodel',
            name='semester',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=1),
        ),
    ]
