# Generated by Django 4.1.2 on 2022-10-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjectApp', '0007_alter_semestersmodel_syllubus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestersmodel',
            name='syllubus',
        ),
    ]
