# Generated by Django 4.1.2 on 2022-10-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectApp', '0008_remove_semestersmodel_syllubus'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestersmodel',
            name='document',
            field=models.FileField(default=0, upload_to='uploads/'),
        ),
    ]
