# Generated by Django 4.1.2 on 2022-10-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectApp', '0009_semestersmodel_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestersmodel',
            name='document',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
