# Generated by Django 4.1.2 on 2022-10-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectApp', '0010_alter_semestersmodel_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestersmodel',
            name='subject_credits',
            field=models.FloatField(),
        ),
    ]
